### PR TITLE
Build NumPy and SciPy against AOCL

### LINKED ISSUE #223: Build Numpy and Scipy against vendor math libraries (AOCL/MKL)
Perhaps this could be done analogously to: https://github.com/tikk3r/flocs/pull/222. There are .pc files in the package, but only for FFTW.

These are the .so filenames used elsewhere in the recipe:
```
-DBLAS_LIBRARIES="${AOCL_ROOT}/lib/libblis.so"
-DLAPACK_LIBRARIES="${AOCL_ROOT}/lib/libflame.so"
```

### PR DESCRIPTION
**Pull request by AlexKurek**
# Description

Try to do the same: https://github.com/tikk3r/flocs/pull/229 here.
Note that numpy and scipy are removed from requirements.txt, so this should me merged at the same time: https://github.com/tikk3r/flocs/pull/222.

### CODE REVIEW

**Comment by AlexKurek** [comment]
Currently:
> Preparing metadata (pyproject.toml): finished with status 'error'

and:

> ../numpy/core/src/common/npy_cpu_dispatch.h:36:14: fatal error: npy_cpu_dispatch_config.h: No such file or directory
>    36 |     #include "npy_cpu_dispatch_config.h"

It seems it was a distutils related file located in `numpy/distutils/include/npy_cpu_dispatch_config.h`.
Disabling the dispacher (https://github.com/tikk3r/flocs/pull/232/commits/34fc9fe3fa85e551b3b547138b3f7c1090f61605) does not help.

Important:
> Run-time dependency scipy-openblas found: NO (tried pkgconfig)
> Run-time dependency aocl-blas found: YES
> Message: BLAS symbol suffix:
> Run-time dependency aocl-lapack found: YES
> [...]
> User defined options
> [...]
>   blas-order  : AOCL-BLAS,openblas
>   lapack-order: AOCL-LAPACK,openblas

But there are **a lot** of `AVX512` etc. occurrences. Seems worth doing.

**Comment by AlexKurek** [comment]
.pc files are wrong:
`cat AOCL-BLAS.pc`
> libdir=/opt/aocl/4.0/lib
> includedir=/opt/aocl/4.0/include
> version= 4.0
> Name: AOCL-BLAS
> Description: AOCL-BLAS Perf Libraries
> Version:
> Cflags: -I
> Libs: -L -lAOCL-BLAS

**Comment by AlexKurek** [comment]
Now:
> /usr/bin/ld: cannot find -lAOCL-BLAS: No such file or directory
> /usr/bin/ld: cannot find -lAOCL-LAPACK: No such file or directory

**Comment by AlexKurek** [comment]
Both numpy and scipy do build now.

**Comment by AlexKurek** [comment]
Only test fails after removing numpy and scipy from requirements.txt. The container is built fine.

**Comment by tikk3r** [comment]
Thanks, nice to be able to build them with vendor libraries. The tests will have to succeed before it can be merged.

It would also be nice to include some results to see if it gives any performance benefit or how much.

**Comment by tikk3r** [comment]
Same as for #231. The test will have to be fixed.

**Comment by AlexKurek** [comment]
> The tests will have to succeed before it can be merged.

I dont understand how it could be failing since numpy is installed in the test (https://github.com/tikk3r/flocs/blob/fedora-py3/.github/workflows/integration-tests.yml#L31C38-L31C48).
One way to fix the tests is to bring back numpy and scipy in requirements.txt.

**Comment by AlexKurek** [comment]
Test is OK now both here and in MKL version.
