### ISSUE TITLE
PyBDSF instalation

### ISSUE THREAD

**Issue by AlexKurek** [tikk3r/lofar-grid-hpccloud#174]
**Describe the bug**
PyBDSF is installed in a strange way, both by clonning and then from PyPi. Is this intentional?
```
mkdir -p ${INSTALLDIR}/pybdsf
cd ${INSTALLDIR}/pybdsf && git clone https://github.com/lofar-astron/pybdsf && cd ${INSTALLDIR}/pybdsf/pybdsf && git checkout ${PYBDSF_VERSION} && echo export PYBDSF_VERSION=$(git rev-parse --short HEAD) >> $INSTALLDIR/init.sh
cd ${INSTALLDIR}/pybdsf/pybdsf
pip install bdsf
```

**Expected behaviour**
Install PyBDSF either by clonning or by `pip install bdsf`

**Logs or error messages**
```
+ cd /opt/lofar/pybdsf/pybdsf
+ pip install bdsf
Collecting bdsf
  Downloading bdsf-1.12.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (44 kB)
```

**Additional information (if applicable or known):**
Installing from source:
`pip install .`
produces:
```
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 999, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/tmp/pip-build-env-f0li1stg/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/tmp/pip-build-env-f0li1stg/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/tmp/pip-build-env-f0li1stg/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2191, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
FATAL:   While performing build: while running engine: while running %post section: exit status 1
```
@gmloose are you aware of this crash?
Python 3.12, Fedora 40.

**Comment by gmloose** [comment]
I don't know who is building PyBDSF in this incorrect way. Looks like you're not following the installation instructions in the `README.rst` file.

Which version of `pybdsf` are you checking out? I.e., what value does `PYBDSF_VERSION` have? I cannot reproduce the issue you face when building from source, but you may be checking out a version that is too old to work with Python 3.12.

**Comment by AlexKurek** [comment]
Its [720f5c30d1c211c0ab14febbee0f8dcefc2c8633](https://github.com/lofar-astron/PyBDSF/commit/720f5c30d1c211c0ab14febbee0f8dcefc2c8633). The version is obviously too old, sorry I missed that.

**Comment by tikk3r** [comment]
Good catch. Looks like I must have forgotten to remove those lines or tried to install be `bdsf` subfolder. In any case this is a bug. It looks like they don't do anything though and the pip command takes care of everything hence it flew under the radar.

@gmloose hi, it's Frits :yum:

**Comment by tikk3r** [comment]
Fixed with #175
